name: quantum-demo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - appmode
  - traitlets<5.10.0
  - pip
  - pip:
      - amplify>=1.0.0
      - dwave-system>=1.3.0
      - minorminer>=0.2.5
      - japanmap
      - matplotlib
      - numpy
      - ipywidgets
      - geopy
      - folium
      - pandas
      - torch
      - scikit-learn
      - sigfig
      - ipympl
      - tqdm
