name: quantum-demo
channels:
  - conda-forge
dependencies:
  - appmode
  - pip
  - pip:
      - amplify>=0.6.5
      - dwave-system>=1.3.0
      - minorminer>=0.2.5
      - japanmap
      - matplotlib
      - numpy
      - ipywidgets<8.0.0
      - geopy
      - folium
      - pandas
      - sklearn
